// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnbwmmgxmypdauxtvure.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuYndtbWd4bXlwZGF1eHR2dXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTIzODAsImV4cCI6MjA3NDI4ODM4MH0.S41hGygUE_VmNkelnC4y3ohWvw81_xkF8fxOBGenWr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});